services:
  - type: web
    name: omnimarketx-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: PORT
        value: 5000
